src/Entity/PlaceToVisit.php
<?php

namespace App\Entity;

use App\Repository\PlaceToVisitRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PlaceToVisitRepository::class)]
class PlaceToVisit
{

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $nom_lieu = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $address = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $cordonnee_geo = null;
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $destination = null;

    public function getDestination(): ?string
    {
        return $this->destination;
    }

    public function setDestination(?string $destination): void
    {
        $this->destination = $destination;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): void
    {
        $this->image = $image;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomLieu(): ?string
    {
        return $this->nom_lieu;
    }

    public function setNomLieu(?string $nom_lieu): static
    {
        $this->nom_lieu = $nom_lieu;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getCordonneeGeo(): ?string
    {
        return $this->cordonnee_geo;
    }

    public function setCordonneeGeo(?string $cordonnee_geo): static
    {
        $this->cordonnee_geo = $cordonnee_geo;

        return $this;
    }
}

src/Form/PlaceToVisitType.php
<?php

namespace App\Form;

use App\Entity\PlaceToVisit;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File as FileConstraint;
use Symfony\Component\Validator\Constraints\Image;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Form\DataTransformerInterface;
use Symfony\Component\HttpFoundation\File\File;

class PlaceToVisitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_lieu', TextType::class, [
                'attr' => ['class' => 'form-control'],
                'constraints' => [
                    new NotBlank(['message' => 'The name cannot be blank']),
                    new Length([
                        'max' => 255,
                        'maxMessage' => 'The name cannot be longer than {{ limit }} characters',
                    ]),
                ],
            ])
            ->add('description', TextType::class, [
                'attr' => ['class' => 'form-control'],
                'constraints' => [
                    new NotBlank(['message' => 'The description cannot be blank']),
                ],
            ])
            ->add('address', TextType::class, [
                'attr' => ['class' => 'form-control'],
                'constraints' => [
                    new NotBlank(['message' => 'The address cannot be blank']),
                ],
            ])
            ->add('cordonnee_geo', TextType::class, [
                'attr' => ['class' => 'form-control'],
                'constraints' => [
                    new NotBlank(['message' => 'The coordinates cannot be blank']),
                ],
            ])
            ->add('image', FileType::class, [
                'required' => false,
                'attr' => ['class' => 'form-control'],
                'constraints' => [
                    new FileConstraint([
                        'maxSize' => '5M',
                        'maxSizeMessage' => 'The file is too large ({{ size }} {{ suffix }}). Maximum allowed size is {{ limit }} {{ suffix }}.',
                        'mimeTypes' => ['image/*'],
                        'mimeTypesMessage' => 'Please upload a valid image file.',
                    ]),
                    new Image([
                        'maxWidth' => 1200,
                        'maxHeight' => 1200,
                        'maxWidthMessage' => 'The image is too wide. Maximum allowed width is {{ max_width }}px.',
                        'maxHeightMessage' => 'The image is too high. Maximum allowed height is {{ max_height }}px.',
                    ]),
                ],
            ])
            ->add('destination', TextType::class, [
                'attr' => ['class' => 'form-control'],
                'constraints' => [
                    new NotBlank(['message' => 'The destination cannot be blank']),
                ],
            ]);

        // Add view transformer to handle file uploads
        $builder->get('image')->addModelTransformer(new class implements DataTransformerInterface {
            public function transform($value): ?string
            {
                // If the value is already a File object, return its path
                if ($value instanceof File) {
                    return $value->getPathname();
                }

                return null;
            }

            public function reverseTransform($value): ?File
            {
                // If the value is a string (file path), create a File object from it
                if (is_string($value)) {
                    return new File($value);
                }

                return null;
            }
        });
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => PlaceToVisit::class,
        ]);
    }
}

src/Controller/PlaceToVisitController.php
<?php

namespace App\Controller;

use App\Entity\PlaceToVisit;
use App\Form\PlaceToVisitType;
use App\Repository\PlaceToVisitRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Knp\Component\Pager\PaginatorInterface;


#[Route('/place/to/visit')]
class PlaceToVisitController extends AbstractController
{
    #[Route('/', name: 'app_place_to_visit_index', methods: ['GET'])]
    public function index(PlaceToVisitRepository $placeToVisitRepository, Request $request, PaginatorInterface $paginator): Response
    {
        $searchQuery = $request->query->get('q');
        $queryBuilder = $placeToVisitRepository->createQueryBuilder('p');

        if ($searchQuery) {
            $queryBuilder
                ->where('p.nom_lieu LIKE :searchQuery')
                ->orWhere('p.description LIKE :searchQuery')
                ->orWhere('p.address LIKE :searchQuery')
                ->orWhere('p.cordonnee_geo LIKE :searchQuery')
                ->orWhere('p.destination LIKE :searchQuery')
                ->setParameter('searchQuery', '%' . $searchQuery . '%');
        }

        $query = $queryBuilder->getQuery();
        $pagination = $paginator->paginate(
            $query, // Query to paginate
            $request->query->getInt('page', 1), // Page number
            3 // Limit per page
        );
     //   $destinationsWithReviewCount = $placeToVisitRepository->countReviewsForDestinations();

        return $this->render('place_to_visit/index.html.twig', [
            'pagination' => $pagination,
            'searchQuery' => $searchQuery,

        ]);
    }
    #[Route('/Front', name: 'app_place_to_visit_front', methods: ['GET'])]
    public function frontList(PlaceToVisitRepository $placeToVisitRepository, Request $request, PaginatorInterface $paginator): Response
    {
        $searchQuery = $request->query->get('q');
        $queryBuilder = $placeToVisitRepository->createQueryBuilder('p');

        if ($searchQuery) {
            $queryBuilder
                ->where('p.nom_lieu LIKE :searchQuery')
                ->orWhere('p.description LIKE :searchQuery')
                ->orWhere('p.address LIKE :searchQuery')
                ->orWhere('p.cordonnee_geo LIKE :searchQuery')
                ->orWhere('p.destination LIKE :searchQuery')
                ->setParameter('searchQuery', '%' . $searchQuery . '%');
        }

        $query = $queryBuilder->getQuery();
        $pagination = $paginator->paginate(
            $query, // Query to paginate
            $request->query->getInt('page', 1), // Page number
            10 // Limit per page
        );
        //   $destinationsWithReviewCount = $placeToVisitRepository->countReviewsForDestinations();

        return $this->render('place_to_visit/listFront.html.twig', [
            'pagination' => $pagination,
            'searchQuery' => $searchQuery,

        ]);
    }
    #[Route('/new', name: 'app_place_to_visit_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $placeToVisit = new PlaceToVisit();
        $form = $this->createForm(PlaceToVisitType::class, $placeToVisit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($placeToVisit);
            $entityManager->flush();

            return $this->redirectToRoute('app_place_to_visit_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('place_to_visit/new.html.twig', [
            'place_to_visit' => $placeToVisit,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_place_to_visit_show', methods: ['GET'])]
    public function show(PlaceToVisit $placeToVisit): Response
    {
        return $this->render('place_to_visit/show.html.twig', [
            'place_to_visit' => $placeToVisit,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_place_to_visit_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, PlaceToVisit $placeToVisit, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PlaceToVisitType::class, $placeToVisit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_place_to_visit_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('place_to_visit/edit.html.twig', [
            'place_to_visit' => $placeToVisit,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_place_to_visit_delete', methods: ['POST'])]
    public function delete(Request $request, PlaceToVisit $placeToVisit, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$placeToVisit->getId(), $request->request->get('_token'))) {
            $entityManager->remove($placeToVisit);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_place_to_visit_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/place_to_visit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}PlaceToVisit index{% endblock %}

{% block body %}
    <div class="container mt-5">
        <h1 class="text-center mb-4">PlaceToVisit Index</h1>
        {# Search Form #}
        <form action="{{ path('app_place_to_visit_index') }}" method="GET" class="mb-3">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..." value="{{ searchQuery }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="submit">Search</button>
                </div>
            </div>
        </form>
        <table class="table">
            <thead>
            <tr>
                <th>Id</th>
                <th>Nom lieu</th>
                <th>Description</th>
                <th>Address</th>
                <th>Coordonnee geo</th>
                <th>Image</th>
                <th>Destination</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for place_to_visit in pagination %}
                <tr>
                    <td>{{ place_to_visit.id }}</td>
                    <td>{{ place_to_visit.nomLieu }}</td>
                    <td>{{ place_to_visit.description }}</td>
                    <td>{{ place_to_visit.address }}</td>
                    <td>{{ place_to_visit.cordonneeGeo }}</td>
                    <td>{{ place_to_visit.image }}</td>
                    <td>{{ place_to_visit.destination }}</td>

                    <td>
                        <a href="{{ path('app_place_to_visit_show', {'id': place_to_visit.id}) }}" class="btn btn-primary">Show</a>
                        <a href="{{ path('app_place_to_visit_edit', {'id': place_to_visit.id}) }}" class="btn btn-secondary">Edit</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="8">No records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <a href="{{ path('app_place_to_visit_new') }}" class="btn btn-success">Create new</a>


        {# Pagination Buttons #}
        <nav aria-label="Pagination">
            <ul class="pagination justify-content-center">
                {% if pagination.currentPageNumber != 1 %}
                    <li class="page-item">
                        <a class="page-link" href="{{ path('app_place_to_visit_index', {'page': 1}) }}">First</a>
                    </li>
                {% endif %}

                {% for page in 1..pagination.pageCount %}
                    <li class="page-item{% if page == pagination.currentPageNumber %} active{% endif %}">
                        <a class="page-link" href="{{ path('app_place_to_visit_index', {'page': page}) }}">{{ page }}</a>
                    </li>
                {% endfor %}

                {% if pagination.currentPageNumber != pagination.pageCount %}
                    <li class="page-item">
                        <a class="page-link" href="{{ path('app_place_to_visit_index', {'page': pagination.pageCount}) }}">Last</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
        <!-- Spinner Start -->
    <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    <!-- Spinner End -->

{% endblock %}

templates/place_to_visit/listFront.html.twig
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Tourist - Travel Agency HTML Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">
    <!-- Google Web Fonts -->
    <link rel="preconnect" href="{{asset('https://fonts.googleapis.com')}}">
    <link rel="preconnect" href="{{asset('https://fonts.gstatic.com')}}" crossorigin>
    <link href="{{asset('https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap')}}" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="{{asset('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css')}}" rel="stylesheet">
    <link href="{{asset('https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css')}}" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{{asset('lib/animate/animate.min.css')}}" rel="stylesheet">
    <link href="{{asset('lib/owlcarousel/assets/owl.carousel.min.css')}}" rel="stylesheet">
    <link href="{{asset('lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css')}}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{{asset('css/bootstrap.min.css')}}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{{asset('css/style.css')}}" rel="stylesheet">

</head>

<body>
<!-- Spinner Start -->
<div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
    <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
        <span class="sr-only">Loading...</span>
    </div>
</div>
<!-- Spinner End -->


<!-- Topbar Start -->
<div class="container-fluid bg-dark px-5 d-none d-lg-block">
    <div class="row gx-0">
        <div class="col-lg-8 text-center text-lg-start mb-2 mb-lg-0">
            <div class="d-inline-flex align-items-center" style="height: 45px;">
                <small class="me-3 text-light"><i class="fa fa-map-marker-alt me-2"></i>123 Street, New York, USA</small>
                <small class="me-3 text-light"><i class="fa fa-phone-alt me-2"></i>+012 345 6789</small>
                <small class="text-light"><i class="fa fa-envelope-open me-2"></i>info@example.com</small>
            </div>
        </div>
        <div class="col-lg-4 text-center text-lg-end">
            <div class="d-inline-flex align-items-center" style="height: 45px;">
                <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href=""><i class="fab fa-twitter fw-normal"></i></a>
                <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href=""><i class="fab fa-facebook-f fw-normal"></i></a>
                <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href=""><i class="fab fa-linkedin-in fw-normal"></i></a>
                <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href=""><i class="fab fa-instagram fw-normal"></i></a>
                <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle" href=""><i class="fab fa-youtube fw-normal"></i></a>
            </div>
        </div>
    </div>
</div>
<!-- Topbar End -->


<!-- Navbar & Hero Start -->
<div class="container-fluid position-relative p-0">
    <nav class="navbar navbar-expand-lg navbar-light px-4 px-lg-5 py-3 py-lg-0">
        <a href="" class="navbar-brand p-0">
            <h1 class="text-primary m-0"><i class="fa fa-map-marker-alt me-3"></i>Tourist</h1>
            <!-- <img src="img/logo.png" alt="Logo"> -->
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="fa fa-bars"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto py-0">
                <a href="index.html" class="nav-item nav-link">Home</a>
                <a href="about.html" class="nav-item nav-link">About</a>
                <a href="service.html" class="nav-item nav-link">Services</a>
                <a href="package.html" class="nav-item nav-link">Packages</a>
                <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle active" data-bs-toggle="dropdown">Pages</a>
                    <div class="dropdown-menu m-0">
                        <a href="destination.html" class="dropdown-item active">Destination</a>
                        <a href="booking.html" class="dropdown-item">Booking</a>
                        <a href="team.html" class="dropdown-item">Travel Guides</a>
                        <a href="testimonial.html" class="dropdown-item">Testimonial</a>
                        <a href="404.html" class="dropdown-item">404 Page</a>
                    </div>
                </div>
                <a href="contact.html" class="nav-item nav-link">Contact</a>
            </div>
            <a href="" class="btn btn-primary rounded-pill py-2 px-4">Register</a>
        </div>
    </nav>

    <div class="container-fluid bg-primary py-5 mb-5 hero-header">
        <div class="container py-5">
            <div class="row justify-content-center py-5">
                <div class="col-lg-10 pt-lg-5 mt-lg-5 text-center">
                    <h1 class="display-3 text-white animated slideInDown">Destination</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-center">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item"><a href="#">Pages</a></li>
                            <li class="breadcrumb-item text-white active" aria-current="page">Destination</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Navbar & Hero End -->


<!-- Destination Start -->
<div class="container-xxl py-5 destination">
    <div class="container">
        <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
            <h6 class="section-title bg-white text-center text-primary px-3">Destination</h6>
            <h1 class="mb-5">Popular Destination</h1>
        </div>
        <div class="row g-3">
            {% for place_to_visit in pagination %}
                <div class="col-lg-7 col-md-6">
                    <div class="row g-3">
                        <div class="col-lg-12 col-md-12 wow zoomIn" data-wow-delay="0.1s">
                            <a class="position-relative d-block overflow-hidden" href="#">
                                {% if place_to_visit.image %}
                                    <img class="img-fluid" src="{{ asset(place_to_visit.image) }}" alt="{{ place_to_visit.nomLieu }}">
                                {% else %}
                                    <!-- Provide a fallback image or handle the null case -->
                                    <img class="img-fluid" src="{{ asset('img/destination-1.jpg') }}" alt="Default Image">
                                {% endif %}
                                <div class="bg-white text-danger fw-bold position-absolute top-0 start-0 m-3 py-1 px-2">30% OFF</div>
                                <div class="bg-white text-primary fw-bold position-absolute bottom-0 end-0 m-3 py-1 px-2">{{ place_to_visit.destination }}</div>
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
<!-- Destination End -->



<!-- Footer Start -->
<div class="container-fluid bg-dark text-light footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
    <div class="container py-5">
        <div class="row g-5">
            <div class="col-lg-3 col-md-6">
                <h4 class="text-white mb-3">Company</h4>
                <a class="btn btn-link" href="">About Us</a>
                <a class="btn btn-link" href="">Contact Us</a>
                <a class="btn btn-link" href="">Privacy Policy</a>
                <a class="btn btn-link" href="">Terms & Condition</a>
                <a class="btn btn-link" href="">FAQs & Help</a>
            </div>
            <div class="col-lg-3 col-md-6">
                <h4 class="text-white mb-3">Contact</h4>
                <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>123 Street, New York, USA</p>
                <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
                <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@example.com</p>
                <div class="d-flex pt-2">
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <h4 class="text-white mb-3">Gallery</h4>
                <div class="row g-2 pt-2">
                    <div class="col-4">
                        <img class="img-fluid bg-light p-1" src="img/package-1.jpg" alt="">
                    </div>
                    <div class="col-4">
                        <img class="img-fluid bg-light p-1" src="img/package-2.jpg" alt="">
                    </div>
                    <div class="col-4">
                        <img class="img-fluid bg-light p-1" src="img/package-3.jpg" alt="">
                    </div>
                    <div class="col-4">
                        <img class="img-fluid bg-light p-1" src="img/package-2.jpg" alt="">
                    </div>
                    <div class="col-4">
                        <img class="img-fluid bg-light p-1" src="img/package-3.jpg" alt="">
                    </div>
                    <div class="col-4">
                        <img class="img-fluid bg-light p-1" src="img/package-1.jpg" alt="">
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <h4 class="text-white mb-3">Newsletter</h4>
                <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
                <div class="position-relative mx-auto" style="max-width: 400px;">
                    <input class="form-control border-primary w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                    <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="copyright">
            <div class="row">
                <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                    &copy; <a class="border-bottom" href="#">Your Site Name</a>, All Right Reserved.

                    <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                    Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a>
                </div>
                <div class="col-md-6 text-center text-md-end">
                    <div class="footer-menu">
                        <a href="">Home</a>
                        <a href="">Cookies</a>
                        <a href="">Help</a>
                        <a href="">FQAs</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Footer End -->


<!-- Back to Top -->
<a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>


<!-- JavaScript Libraries -->
<script src="{{asset('https://code.jquery.com/jquery-3.4.1.min.js')}}"></script>
<script src="{{asset('https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js')}}"></script>
<script src="{{asset('lib/wow/wow.min.js')}}"></script>
<script src="{{asset('lib/easing/easing.min.js')}}"></script>
<script src="{{asset('lib/waypoints/waypoints.min.js')}}"></script>
<script src="{{asset('lib/owlcarousel/owl.carousel.min.js')}}"></script>
<script src="{{asset("lib/tempusdominus/js/moment.min.js")}}"></script>
<script src="{{asset('lib/tempusdominus/js/moment-timezone.min.js')}}"></script>
<script src="{{asset('lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js')}}"></script>
<script src="{{asset('js/main.js')}}"></script>

<!-- Template Javascript -->
<script src="js/main.js"></script>
</body>

</html>

templates/place_to_visit/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}PlaceToVisit{% endblock %}

{% block body %}
    <h1>PlaceToVisit</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ place_to_visit.id }}</td>
            </tr>
            <tr>
                <th>Nom_lieu</th>
                <td>{{ place_to_visit.nomLieu }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ place_to_visit.description }}</td>
            </tr>
            <tr>
                <th>Address</th>
                <td>{{ place_to_visit.address }}</td>
            </tr>
            <tr>
                <th>Cordonnee_geo</th>
                <td>{{ place_to_visit.cordonneeGeo }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ place_to_visit.image }}</td>
            </tr>
            <tr>
                <th>Destination</th>
                <td>{{ place_to_visit.destination }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_place_to_visit_index') }}">back to list</a>

    <a href="{{ path('app_place_to_visit_edit', {'id': place_to_visit.id}) }}">edit</a>

    {{ include('place_to_visit/_delete_form.html.twig') }}
{% endblock %}