src/Entity/Reponse.php
<?php

namespace App\Entity;

use App\Repository\ReponseRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: ReponseRepository::class)]
class Reponse
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 500)]
    #[Assert\NotBlank(message : "This field should not be blank.")]
    private ?string $description = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\OneToOne(inversedBy: 'reponse', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Reclamation $id_rec = null;

    #[ORM\Column]
    private ?int $id_user = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getIdRec(): ?Reclamation
    {
        return $this->id_rec;
    }

    public function setIdRec(Reclamation $id_rec): static
    {
        $this->id_rec = $id_rec;

        return $this;
    }

    public function getIdUser(): ?int
    {
        return $this->id_user;
    }

    public function setIdUser(int $id_user): static
    {
        $this->id_user = $id_user;

        return $this;
    }
}

src/Form/ReviewsType.php
<?php

namespace App\Form;

use App\Entity\Reviews;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReviewsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('commentaire', TextareaType::class, [
                'label' => 'Your Review',
                'attr' => [
                    'class' => 'form-control',
                    'rows' => 5, // Adjust the number of rows as needed
                    'placeholder' => 'Write your review here...',
                ],
            ])
            // You may want to add more fields like rating, if applicable
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reviews::class,
        ]);
    }
}

src/Controller/ReviewsController.php
<?php

namespace App\Controller;

use App\Entity\Reviews;
use App\Form\ReviewsType;
use App\Repository\ReviewsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/reviews')]
class ReviewsController extends AbstractController
{
    #[Route('/', name: 'app_reviews_index', methods: ['GET'])]
    public function index(ReviewsRepository $reviewsRepository): Response
    {
        return $this->render('reviews/index.html.twig', [
            'reviews' => $reviewsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_reviews_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $review = new Reviews();
        $form = $this->createForm(ReviewsType::class, $review);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($review);
            $entityManager->flush();

            return $this->redirectToRoute('app_reviews_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('reviews/new.html.twig', [
            'review' => $review,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_reviews_show', methods: ['GET'])]
    public function show(Reviews $review): Response
    {
        return $this->render('reviews/show.html.twig', [
            'review' => $review,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_reviews_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Reviews $review, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ReviewsType::class, $review);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_reviews_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('reviews/edit.html.twig', [
            'review' => $review,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_reviews_delete', methods: ['POST'])]
    public function delete(Request $request, Reviews $review, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$review->getId(), $request->request->get('_token'))) {
            $entityManager->remove($review);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_reviews_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/reviews/_delete_form.html.twig
<form method="post" action="{{ path('app_reviews_delete', {'id': review.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ review.id) }}">
    <button class="btn">Delete</button>
</form>

templates/reviews/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/reviews/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Reviews{% endblock %}

{% block body %}
    <h1>Edit Reviews</h1>

    {{ include('reviews/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_reviews_index') }}">back to list</a>

    {{ include('reviews/_delete_form.html.twig') }}
{% endblock %}

templates/reviews/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reviews index{% endblock %}

{% block body %}
    <h1>Reviews index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Id_User</th>
                <th>Commentaire</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for review in reviews %}
            <tr>
                <td>{{ review.id }}</td>
                <td>{{ review.idUser }}</td>
                <td>{{ review.commentaire }}</td>
                <td>
                    <a href="{{ path('app_reviews_show', {'id': review.id}) }}" class="btn btn-primary">Show</a>
                    <a href="{{ path('app_reviews_edit', {'id': review.id}) }} " class="btn btn-secondary">Edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_reviews_new') }}" class="btn btn-success">Create new</a>
{% endblock %}

templates/reviews/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Reviews{% endblock %}

{% block body %}
    <h1>Create new Reviews</h1>

    {{ include('reviews/_form.html.twig') }}

    <a href="{{ path('app_reviews_index') }}">back to list</a>
{% endblock %}

templates/reviews/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reviews{% endblock %}

{% block body %}
    <h1>Reviews</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ review.id }}</td>
            </tr>
            <tr>
                <th>Id_User</th>
                <td>{{ review.idUser }}</td>
            </tr>
            <tr>
                <th>Commentaire</th>
                <td>{{ review.commentaire }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_reviews_index') }}">back to list</a>

    <a href="{{ path('app_reviews_edit', {'id': review.id}) }}">edit</a>

    {{ include('reviews/_delete_form.html.twig') }}
{% endblock %}